name: Build Kernel Driver

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Clone Kernel Source
    - name: Clone Kernel Source
      run: |
        git clone https://github.com/Ujjwal-afk/kernel_oplus_RMX3461_-cocaine- kernel_source
        cd kernel_source && git checkout kernel-branch-name  # Replace 'kernel-branch-name' with the correct branch

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          make \
          libssl-dev \
          build-essential \
          bc \
          bison \
          flex \
          ca-certificates \
          xz-utils \
          device-tree-compiler \
          git

    # Step 4: Build Kernel Module
    - name: Build Kernel Module
      run: |
        export KDIR=$(pwd)/kernel_source
        make -C $KDIR M=$(pwd) modules

    # Step 5: Prepare AnyKernel3
    - name: Setup AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3
        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
        sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
        sed -i 's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
        rm -rf AnyKernel3/.git* AnyKernel3/README.md
        cp overlay.ko AnyKernel3/modules/

    # Step 6: Upload Flashable Zip
    - name: Upload Flashable Zip
      uses: actions/upload-artifact@v4
      with:
        name: Kernel_Driver_Zip
        path: AnyKernel3/*
